name: Check Formatting

on:
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Check formatting with Prettier
        run: bun run format:check
